"""
plot_class_distribution.py
--------------------------
Purpose:
    Generates a histogram showing the distribution of classes across
    training, validation, and testing splits. This visual verification
    corresponds to the 'Histogram plots of class distribution' deliverable
    mentioned in the meeting slides.

Rationale:
    A balanced dataset across splits ensures fair model training and
    evaluation. Class imbalance can bias a classifier towards majority
    classes. Therefore, this plot visually confirms the success of the
    stratified 70/15/15 split performed during dataset preparation.

Dependencies:
    - pandas
    - matplotlib
    - seaborn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Path to dataset summary CSV generated by dataset_prep.py
SUMMARY_PATH = Path("results/dataset_summary.csv")

def main():
    # Step 1: Readin' the dataset summary generated in the preparation stage
    df = pd.read_csv(SUMMARY_PATH)
    print(f"[INFO] Loaded dataset summary ({len(df)} records).")

    # Step 2: Initialisin' the plotting environment
    plt.figure(figsize=(7, 4))
    sns.set_style("whitegrid")

    # Step 3: Plottin' class distribution for each split
    sns.barplot(data=df, x="class", y="count", hue="split", palette="muted")

    # Step 4: Adding descriptive titles and labels
    plt.title("Class Distribution Across Splits", fontsize=13, weight="bold")
    plt.xlabel("Tumour Class")
    plt.ylabel("Number of Images")

    # Step 5: Savin' plot to the results folder and display
    output_path = Path("results/class_distribution_histogram.png")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.show()

    print(f"[INFO] Histogram saved to {output_path.resolve()}")

if __name__ == "__main__":
    main()
